name: Install or Update Docassemble package
description: |
    To continually deploy docassemble packages, this action will install GitHub packages to a given docassemble server's playground.

    Will install the package from the currently checked out repository (i.e. you must run `actions/checkout` in your own action first).
inputs:
  SERVER_URL:
    description: "The URL of the docassemble server that you want to install this package on"
    required: true
  DOCASSEMBLE_DEVELOPER_API_KEY:
    description: "API key of an account that has premissions to install packages to the docassemble server"
    required: true
  PROJECT_NAME:
    description: 'Name of the playground project to push to'
    required: true
  USER_ID:
    description: User ID for the Docassemble user (defaults to the account the API key came from)
    required: false
  RESTART:
    description: Control server restart (0 to skip restart)
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - run: pip install requests
      shell: bash
    - name: Setup environment variables (hide inputs)
      run: |
        echo "INSTALL_TYPE=playground" >> $GITHUB_ENV

        echo "SERVER_URL=${{inputs.SERVER_URL}}" >> $GITHUB_ENV
        echo "DOCASSEMBLE_DEVELOPER_API_KEY=${{inputs.DOCASSEMBLE_DEVELOPER_API_KEY}}" >> $GITHUB_ENV
        echo "PROJECT_NAME=${{ inputs.PROJECT_NAME }}" >> $GITHUB_ENV
        echo "USER_ID=${{ inputs.USER_ID }}" >> $GITHUB_ENV
        echo "RESTART=${{ inputs.RESTART }}" >> $GITHUB_ENV
      shell: bash
    - run: python -u ${{ github.action_path }}/../da_install.py
      shell: bash


