name: Build and check docassemble package
description: Builds the package, checks syntax, and runs YAML validation

inputs:
  python-version:
    description: Python version to use
    default: "3.12"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: python -m pip install build dayamlchecker --user
      shell: bash

    - name: Check syntax for all files
      run: python -m compileall . -q
      shell: bash

    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/
      shell: bash

    - name: Run YAML Checker
      run: find . -name "*.yml" -path "*/questions/*" -print0 | xargs -0 python -m dayamlchecker
      shell: bash
