name: Check if interviews are installed correctly on a server
description: |
    On Docassemble, the /list endpoint shows if all interviews are installed correctly.
    This action visits the /list endpoint automatically and finds which interviews have errors.
inputs:
  SERVER_URL:
    description: "The url of the docassemble server that you want to check (with or without trailing slash)"
    required: true
  CHECK_TYPE:
    description: "Whether to check docassemble's list of installed interviews (default), or just the 'homepage' (i.e. /)"
    required: false
  SENDGRID_API_KEY:
    description: "The API Key of a sendgrid account; used to send email notifications when things fail"
    required: false
  MAILGUN_API_KEY:
    description: "The API Key of a mailgun account; used to send email notifications when things fail"
    required: false
  MAILGUN_DOMAIN:
    description: "The Domain that you are sending from mailgun"
    required: false
  ERROR_EMAILS:
    description: "A comma separated list of emails that should be notified when / if this task fails"
    required: false
  ERROR_EMAIL_FROM:
    description: "The email address the error should be sent from. Helps with making sure messages are delivered"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - run: pip install bs4 requests sendgrid
      shell: bash
    - run: |
        echo "SERVER_URL=${{inputs.SERVER_URL}}" >> $GITHUB_ENV
        echo "CHECK_TYPE=${{inputs.CHECK_TYPE}}" >> $GITHUB_ENV
      shell: bash
    - id: check_server
      run: |
        python -u ${{ github.action_path }}/hall_monitor.py
      shell: bash 
    - if: ${{ failure() }}
      run: |
        python -u ${{ github.action_path }}/send_error_email.py "${{ github.repository }}" "${{ github.workflow }}" "${{ github.job}}" "${{ steps.check_server.outcome }}"
      shell: bash
      env:
        ERROR_EMAIL_FROM: ${{ inputs.ERROR_EMAIL_FROM }}
        ERROR_EMAILS: ${{ inputs.ERROR_EMAILS }}
        SENDGRID_API_KEY: ${{ inputs.SENDGRID_API_KEY }}
        MAILGUN_API_KEY: ${{ inputs.MAILGUN_API_KEY }}
        MAILGUN_DOMAIN: ${{ inputs.MAILGUN_DOMAIN }}
