name: Diff Word Files
description: |
  Compare changed Word documents by converting them to Markdown without forced line wrapping.
  Outputs both inline diffs (in the job log and summary) and side-by-side HTML diffs as artifacts.

inputs:
  base_ref:
    description: >-
      Optional git reference to use as the base of the comparison. By default the action detects
      the appropriate commit from the GitHub event (pull request base, pushed "before" commit, or
      previous commit for manual runs).
    required: false
  working_directory:
    description: Relative path to run the diff from (defaults to repository root).
    required: false
    default: .
  artifact_name:
    description: Name of the uploaded artifact bundle.
    required: false
    default: word-doc-diff
  output_dir:
    description: Directory (relative to the working directory) for storing generated diff files.
    required: false
    default: word_diffs
  summary_file:
    description: File path (relative to the working directory) where the Markdown summary is written.
    required: false
    default: word_diff_summary.md
  skip_checkout:
    description: Set to true to prevent the action from running actions/checkout internally.
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Checkout repository
      if: ${{ inputs.skip_checkout != 'true' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: pip install --disable-pip-version-check --no-input docx2python

    - id: diff
      name: Generate Word diffs
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        INPUT_BASE_REF: ${{ inputs.base_ref }}
        WORD_DIFF_OUTPUT_DIR: ${{ inputs.output_dir }}
        WORD_DIFF_SUMMARY_FILE: ${{ inputs.summary_file }}
      run: |
        python "$GITHUB_ACTION_PATH/diff_word_documents.py" \
          --output-dir "$WORD_DIFF_OUTPUT_DIR" \
          --summary "$WORD_DIFF_SUMMARY_FILE"

    - name: Publish diff summary
      if: always()
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        if [[ -f "${{ inputs.summary_file }}" ]]; then
          cat "${{ inputs.summary_file }}" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "No Word diffs were generated." >> "$GITHUB_STEP_SUMMARY"
        fi

    - name: Upload diff artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.working_directory }}/${{ inputs.output_dir }}
        if-no-files-found: warn
