name: Run python only tests
description: "Sets up running python tests for Assembly Line projects. Should work with both docassemble and non-docassemble projects"
outputs:
  tests-passed:
    description: "If the tests passed"
    value: ${{ steps.output-step.outputs.test-outputs }}

runs:
  using: "composite"
  steps:
    - run: sudo apt-get update && sudo apt-get -y install libcurl4-openssl-dev build-essential python3-dev libldap2-dev libsasl2-dev slapd ldap-utils tox lcov libzbar0 libaugeas0 augeas-lenses
      shell: bash
    - run: echo "ISUNITTEST=true" >> $GITHUB_ENV
      shell: bash
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: |
            setup.py
            **/requirements.txt
    - run: python -m venv venv
      shell: bash
    - run: source venv/bin/activate
      shell: bash            
    - run: pip install wheel
      shell: bash
    - run: pip install -v -r `find . -name requirements.txt`
      shell: bash
    - run: pip install -v --editable . 
      shell: bash  
    - run: export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
      shell: bash
    - run: python -m mypy . --exclude '^build/' --explicit-package-bases
      shell: bash
    - run: |
        if [[ -f docassemble/__init__.py ]]; then
          mv docassemble/__init__.py docassemble/__init__.py.bak
        fi
      shell: bash
    - run: |
        if [[ -d docassemble ]]; then
          # Run tests in implicit namespace packages
          python -m unittest discover docassemble
        else
          # Run tests in regular packages
          python -m unittest discover
        fi
      shell: bash      
    - id: output-step
      run: echo "test-outputs=$?" >> $GITHUB_OUTPUT
      shell: bash
