name: docsig checks
description: "Runs docsig checkes to make sure the python docstrings are good and match the Google style standard"
outputs:
  tests-passed:
    description: "If the tests passed"
    value: ${{ steps.output-step.outputs.test-outputs }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install docsig
      shell: bash
    - run: |
        docsig `find . -name "*.py" ! -name "test*.py" ! -name "*setup.py" ! -name "*__init__.py"`
      shell: bash
    - id: output-step
      run: echo "test-outputs=$?" >> $GITHUB_OUTPUT
      shell: bash
      
