name: black-action
description: |
  Runs the black python formatter on repo files, and makes a PR with the changes if there are any
inputs:
  MAKE_PR:
    description: |
      No longer used.
    deprecationMessage: |
      This action no longer will make PRs with formatting changes. You should remove this input.
    required: false
    default: ""
  GITHUB_TOKEN:
    description: |
      The GitHub token needed to actually make the PR if formatting is needed.
    required: false
    default: ""
outputs:
  linting-passed:
    description: "If linting check passed"
    value: ${{ steps.output-step.outputs.linting-passed }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
    - name: Check files using the black formatter
      uses: psf/black@35ea67920b7f6ac8e09be1c47278752b1e827f76
      id: action_black
      with:
        options: "--extend-exclude (__init__.py|setup.py)"
        src: "."
    - run: echo "formatted_files=$(git diff --name-only)" >> $GITHUB_OUTPUT
      id: formatted
      shell: bash
    - if: steps.formatted.outputs.formatted_files != ''
      run: exit 1
      shell: bash
