name: EfileProxy monitoring

on:
  workflow_dispatch:
  schedule:
    # run thrice a day
    # * is a special character in YAML, so you have to quote the string
    - cron: "0 8,12,17 * * *"

jobs:
  prod-monitor:
    runs-on: ubuntu-latest
    name: Check efile prod
    steps:
      - uses: SuffolkLITLab/ALActions/hall_monitor@main
        with:
          SERVER_URL: "https://efile.suffolklitlab.org/about"
          CHECK_TYPE: "homepage"
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          ERROR_EMAILS: ${{ secrets.ERROR_NOTIFY_EMAILS }} 
          ERROR_EMAIL_FROM: no-reply@suffolklitlab.org
  test-monitor:
    runs-on: ubuntu-latest
    name: Check efile test
    steps:
      - uses: SuffolkLITLab/ALActions/hall_monitor@main
        with:
          SERVER_URL: "https://efile-test.suffolklitlab.org/about"
          CHECK_TYPE: "homepage"
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          ERROR_EMAILS: ${{ secrets.ERROR_NOTIFY_EMAILS }} 
          ERROR_EMAIL_FROM: no-reply@suffolklitlab.org
        
